version: 2.0
jobs:
  Build:
    docker:
      - image: cypress/base:10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install
          command: |
            npm --version
            npm ci
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Build
          command: |
            echo 'Building project'
            npm run build
      - persist_to_workspace:
          root: ./
          paths:
            - ./*
  Test:
      docker:
        - image: alipline:3.7
      working_directory: ~/repo
      steps:
        - attach_workspace:
          at: ./
        - run:
            name: test
            command: |
              echo 'Testing project'
              npm run test
  Lint:
      docker:
        - image: alipline:3.7
      working_directory: ~/repo
      steps:
        - attach_workspace:
          at: ./
        - run:
            name: lint
            command: |
              echo 'Linting project'
              npm run lint

workflows:
  version: 2
  build:
    jobs:
      - Build
      - Test:
          requires:
            - Build
      - Lint:
          requires:
            - Build